AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  send-switchbot-metrics-to-mackerel

  Sample SAM Template for send-switchbot-metrics-to-mackerel

Parameters:
  SwitchBotApiToken:
    Type: String
    Description: "SwitchBot API Token"
  SwitchBotApiSecret:
    Type: String
    Description: "SwitchBot API Secret"
  MackerelApiKey:
    Type: String
    Description: "Mackerel API Key"
  MackerelService:
    Type: String
    Description: "Mackerel Service Name"
  MeterSchedule:
    Type: String
    Description: "Send Metrics Schedule for Meter"
    Default: "cron(*/5 * * * ? *)"
  PlugSchedule:
    Type: String
    Description: "Send Metrics Schedule for Meter"
    Default: "cron(*/5 * * * ? *)"

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 5

    # You can add LoggingConfig parameters such as the Logformat, Log Group, and SystemLogLevel or ApplicationLogLevel. Learn more here https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-resource-function.html#sam-function-loggingconfig.
    LoggingConfig:
      LogFormat: JSON
Resources:
  Meter:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: meter/
      Handler: app.lambdaHandler
      Runtime: nodejs20.x
      Architectures:
      - x86_64
      Events:
        CloudWatchEvent:
          Type: Schedule
          Properties:
            Schedule: !Ref MeterSchedule
      Environment:
        Variables:
            SWITCHBOT_API_TOKEN: !Ref SwitchBotApiToken
            SWITCHBOT_API_SECRET: !Ref SwitchBotApiSecret
            MACKEREL_API_KEY: !Ref MackerelApiKey
            MACKEREL_SERVICE: !Ref MackerelService
    Metadata: # Manage esbuild properties
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: es2020
        Sourcemap: true
        EntryPoints:
        - app.ts
  Plug:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: plug/
      Handler: app.lambdaHandler
      Runtime: nodejs20.x
      Architectures:
      - x86_64
      Events:
        CloudWatchEvent:
          Type: Schedule
          Properties:
            Schedule: !Ref PlugSchedule
      Environment:
        Variables:
            SWITCHBOT_API_TOKEN: !Ref SwitchBotApiToken
            SWITCHBOT_API_SECRET: !Ref SwitchBotApiSecret
            MACKEREL_API_KEY: !Ref MackerelApiKey
            MACKEREL_SERVICE: !Ref MackerelService
    Metadata: # Manage esbuild properties
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: es2020
        Sourcemap: true
        EntryPoints:
        - app.ts
Outputs:
  MeterFunction:
    Description: Meter Lambda Function ARN
    Value: !GetAtt Meter.Arn
  MeterIamRole:
    Description: Implicit IAM Role created for Meter function
    Value: !GetAtt MeterRole.Arn
  PlugFunction:
    Description: Plug Lambda Function ARN
    Value: !GetAtt Plug.Arn
  PlugIamRole:
    Description: Implicit IAM Role created for Plug function
    Value: !GetAtt PlugRole.Arn
